Implemented types for this project
duailibe/unemit pull request #1
Opened 2021-12-02 18:32 UTC by lucasvictor3

2021-12-02 18:54 UTC, lucasvictor3 commented on index.ts
> +type Handler = (event?: any) => void;
Faltou eu remover aqui =x

2021-12-02 18:55 UTC, lucasvictor3 commented on index.ts
> +type Handler = (event: any) => void;
tinha uma issue sobre isso no repo typescript-eslint. Mas alguem fechou porque nao conseguiu reproduzir na master.

2021-12-02 19:02 UTC, duailibe requested changes
You don't need to rename the file to .js

Just add a `index.d.ts` next to `index.js` and TS will pick that up

2021-12-02 21:35 UTC, duailibe reviewed
Much better =)

Now you have to add `index.d.ts` here so it will be included in the package:

https://github.com/duailibe/unemit/blob/50a0694786c5d18afd3686520e8d4338af417e15/package.json#L14-L16

2021-12-02 21:36 UTC, duailibe requested changes
What I said above

2021-12-06 17:12 UTC, duailibe approved these changes

2021-12-06 17:12 UTC, merged